import type { IconBaseProps, IconType } from 'react-icons';
import {
  IoAdd,
  IoAddCircle,
  IoAddCircleOutline,
  IoAddOutline,
  IoAlertCircle,
  IoAlertCircleOutline,
  IoArrowForward,
  IoArrowUp,
  IoBook,
  IoBookOutline,
  IoCamera,
  IoCameraOutline,
  IoCameraReverse,
  IoCheckmark,
  IoCheckmarkCircle,
  IoCheckmarkDone,
  IoCheckmarkDoneOutline,
  IoChevronBack,
  IoChevronForward,
  IoClose,
  IoCloseCircle,
  IoCloudUpload,
  IoCreate,
  IoCreateOutline,
  IoDocumentOutline,
  IoDocumentText,
  IoDownloadOutline,
  IoEaselOutline,
  IoEllipseOutline,
  IoEnterOutline,
  IoEyeOffOutline,
  IoEyeOutline,
  IoFolderOpen,
  IoFolderOpenOutline,
  IoHappy,
  IoHappyOutline,
  IoHome,
  IoHomeOutline,
  IoImages,
  IoInformationCircle,
  IoKey,
  IoKeyOutline,
  IoKeypad,
  IoLibrary,
  IoLibraryOutline,
  IoLinkOutline,
  IoLockClosedOutline,
  IoLogOutOutline,
  IoLogoGoogle,
  IoMail,
  IoMailOpenOutline,
  IoMailOutline,
  IoPeopleOutline,
  IoPerson,
  IoPersonAddOutline,
  IoPersonCircle,
  IoPersonOutline,
  IoRefresh,
  IoScan,
  IoScanOutline,
  IoSchool,
  IoSchoolOutline,
  IoSearch,
  IoShieldCheckmark,
  IoShieldCheckmarkOutline,
  IoSparkles,
  IoSparklesOutline,
  IoTime,
  IoTrashOutline,
  IoTrophyOutline,
} from 'react-icons/io5';

// Ionicons, the same set the Expo app used (@expo/vector-icons), so screens keep their icon names.
const ICONS = {
  'add': IoAdd,
  'add-circle': IoAddCircle,
  'add-circle-outline': IoAddCircleOutline,
  'add-outline': IoAddOutline,
  'alert-circle': IoAlertCircle,
  'alert-circle-outline': IoAlertCircleOutline,
  'arrow-forward': IoArrowForward,
  'arrow-up': IoArrowUp,
  'book': IoBook,
  'book-outline': IoBookOutline,
  'camera': IoCamera,
  'camera-outline': IoCameraOutline,
  'camera-reverse': IoCameraReverse,
  'checkmark': IoCheckmark,
  'checkmark-circle': IoCheckmarkCircle,
  'checkmark-done': IoCheckmarkDone,
  'checkmark-done-outline': IoCheckmarkDoneOutline,
  'chevron-back': IoChevronBack,
  'chevron-forward': IoChevronForward,
  'close': IoClose,
  'close-circle': IoCloseCircle,
  'cloud-upload': IoCloudUpload,
  'create': IoCreate,
  'create-outline': IoCreateOutline,
  'document-outline': IoDocumentOutline,
  'document-text': IoDocumentText,
  'download-outline': IoDownloadOutline,
  'easel-outline': IoEaselOutline,
  'ellipse-outline': IoEllipseOutline,
  'enter-outline': IoEnterOutline,
  'eye-outline': IoEyeOutline,
  'eye-off-outline': IoEyeOffOutline,
  'folder-open': IoFolderOpen,
  'folder-open-outline': IoFolderOpenOutline,
  'happy': IoHappy,
  'happy-outline': IoHappyOutline,
  'home': IoHome,
  'home-outline': IoHomeOutline,
  'images': IoImages,
  'information-circle': IoInformationCircle,
  'key': IoKey,
  'key-outline': IoKeyOutline,
  'keypad': IoKeypad,
  'library': IoLibrary,
  'library-outline': IoLibraryOutline,
  'link-outline': IoLinkOutline,
  'lock-closed-outline': IoLockClosedOutline,
  'log-out-outline': IoLogOutOutline,
  'logo-google': IoLogoGoogle,
  'mail': IoMail,
  'mail-open-outline': IoMailOpenOutline,
  'mail-outline': IoMailOutline,
  'people-outline': IoPeopleOutline,
  'person': IoPerson,
  'person-add-outline': IoPersonAddOutline,
  'person-circle': IoPersonCircle,
  'person-outline': IoPersonOutline,
  'refresh': IoRefresh,
  'scan': IoScan,
  'scan-outline': IoScanOutline,
  'school': IoSchool,
  'school-outline': IoSchoolOutline,
  'search': IoSearch,
  'shield-checkmark': IoShieldCheckmark,
  'shield-checkmark-outline': IoShieldCheckmarkOutline,
  'sparkles': IoSparkles,
  'sparkles-outline': IoSparklesOutline,
  'time': IoTime,
  'trash-outline': IoTrashOutline,
  'trophy-outline': IoTrophyOutline,
} satisfies Record<string, IconType>;

export type IconName = keyof typeof ICONS;

/** Decorative by default; pass a `title` when the icon is the only label. */
export function Icon({ name, size = 20, color, title, ...rest }: { name: IconName; size?: number; color?: string; title?: string } & Omit<IconBaseProps, 'size' | 'color' | 'title'>) {
  const Component = ICONS[name];
  return <Component size={size} color={color} title={title} aria-hidden={title ? undefined : true} focusable={false} {...rest} />;
}
